baseurl: /readmyreadme.io
title: Read My README
description: 나는 무엇을 쓸 수 있을까?
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Collections
collections:
  writings:
    output: true
    permalink: /:collection/:path/

# 추가 옵션
author: a-small-fish
show_downloads: false
